### ISSUE TITLE
[ Install Failed ] cant start dwm

### ISSUE THREAD

**Issue by voltrare** [dimpram/.dotfiles#6]
I am using arch on virtual box using 'archinstall', with minimal setup (no xorg)
I have installed intel ucode, networkmanager, reflector, git

After that I have directly cloned the dotfiles and start the installenv.sh

but it failed with this error
![image](https://user-images.githubusercontent.com/30526233/131158824-f46c93a6-5cbd-4279-869b-24faa48ccc69.png)

i have tried to exit the session and after log in back its in zsh shell but when running the installenv.sh it returns same error

**Comment by dimpram** [comment]
I should probably remove the part of the script that changes the shell because it didn't work properly on my machine either. You can try running zsh manually (just type zsh on a terminal) for the first time setup and after that you can copy my zshrc config (or create your own). If you find a better solution you can always send a PR or reply to this issue :)

**Comment by voltrare** [comment]
thanks!
the latest update got does not give errors ( i just run the script over existing install )
but it does not start dwm 

my network kinda sucks, ill try to run on fresh install

**Comment by dimpram** [comment]
Have you downloaded the git sub modules too? If you haven't then the dwm won't be able to be built and thus it won't be able to start.

**Comment by voltrare** [comment]
yeah there is .gitmodules in the ~/ 
i cant also start the exec dwm 
does it means dwm doesnt built during using script?
the dwm folder in ~/.local/src/dwm is empty too

![image](https://user-images.githubusercontent.com/30526233/131320787-bedb265d-cf1f-4772-b1a1-64d3d464ec1d.png)
maybe its because of this? it cant clone the dwm folder thus cant build dwm

i tried clone with normal git clone https://github.com/dimpram/dwm.git 
then sudo make clean install
then run startx

it runs dwm but not it runs with the default dwm not with the themes

**Comment by voltrare** [comment]
> Have you downloaded the git sub modules too? If you haven't then the dwm won't be able to be built and thus it won't be able to start.

ah now i understand, i have tried with the sub modules downloaded too but it still wont work

**Comment by dimpram** [comment]
Go to the dwm submodule folder and run 

```
sudo make clean install
```

and then restart your xorg session

**Comment by voltrare** [comment]
i tried that too
then i run startx
yeah its running dwm but its kinda looks like vanilla dwm

**Comment by dimpram** [comment]
Please post a screenshot

**Comment by voltrare** [comment]
here
![image](https://user-images.githubusercontent.com/30526233/131769670-3e9a6229-01a1-46b4-94b2-bcbddfaa97f6.png)

*this is after I do " Mod + B " and " Mod + Enter "
I have tried this multiple times with new installation and it keeps be looking like this

**Comment by dimpram** [comment]
That's how it's supposed to look. I don't use the bar and for the rounded corners you need [modded picom](https://github.com/ibhagwan/picom). As for the font, make sure it's installed and that you are using my configs properly.

If you want to check the status of your battery and date and stuff just press `start + s`. This launches a bash script that utilizes dunst for displaying info as a notification.

**Comment by voltrare** [comment]
ah its just that picom failed to start unless I run sudo picom (it only gave transparency) and then the system freezes
for the font how do i make sure its installed as from using the installenvscript's logs it says they're being built and installed

**Comment by dimpram** [comment]
It's hard for me to know exactly what went wrong on your installation so i really can't help you any further. I am pretty sure you can find what went wrong by yourself - you will also learn more this way :)  I think the issue can be closed now.

**Comment by voltrare** [comment]
alright, thank you for the support tho. Sorry for taking your time
